name: Databricks Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Databricks CLI
      - name: Install Databricks CLI
        run: |
          # Download the file
          curl -L https://github.com/databricks/cli/releases/download/v0.295.0/databricks_cli_0.295.0_linux_amd64.tar.gz -o databricks.tar.gz
          
          # Extract it
          tar -xzf databricks.tar.gz
          
          # Move binary to PATH
          sudo mv databricks /usr/local/bin/databricks
          
          # Make executable (just in case)
          sudo chmod +x /usr/local/bin/databricks
          
          # Verify installation
          databricks --version

      # Hardcoded env values
      - name: Bundle deploy
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        run: |
          echo "Host: $DATABRICKS_HOST"
          databricks bundle validate -t dev
          databricks bundle deploy -t dev
